name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
    - name: Install dependencies
      run: dotnet restore MarvelBackend
    - name: Build
      run: dotnet build MarvelBackend --configuration Release --no-restore
    - name: Test
      run: dotnet test MarvelBackend --no-restore --verbosity normal
